server:
  port: 8002

spring:
  application:
    name: eureka-provider
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092         #Kafka的消息中间件服务器
          zk-nodes: localhost:2181        #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
      bindings:
        output1: #通道名称
          binder: kafka
          destination: test1 #消息发往的目的地，对应topic
          group: output-group-1 #对应kafka的group
          content-type: text/plain #消息的格式
eureka:
  client:
    fetch-registry: false # 不向eureka server 获取服务列表
    service-url:
      defaultZone: http://localhost:8001/eureka # 指定服务注册中心
