server:
  port: 8003

spring:
  application:
    name: eureka-Consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092         #Kafka的消息中间件服务器
          zk-nodes: localhost:2181        #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
      bindings:
        input1:
          binder: kafka
          destination: test1
          content-type: text/plain
          group: input-group-1

eureka:
  client:
    fetch-registry: true # 向eureka server 获取服务列表
    service-url:
      defaultZone: http://localhost:8001/eureka # 指定服务注册中心

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。
